// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SparkPens.Api.Data;

#nullable disable

namespace SparkPens.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212125839_CompleteCustomerModule")]
    partial class CompleteCustomerModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SparkPens.Api.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NIM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaMahasiswa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WaktuMulai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WaktuSelesai")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SparkPens.Api.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Address = "Jl. Raya Kampus PENS No. 1",
                            CreatedDate = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "budi.santoso@pens.ac.id",
                            IsDeleted = false,
                            Name = "Budi Santoso",
                            Phone = "081234567890",
                            Status = "active"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a1-4b6c-9d0e-1f2a3b4c5d6e"),
                            Address = "Griya Gebang Blok C-12",
                            CreatedDate = new DateTime(2026, 2, 2, 11, 30, 0, 0, DateTimeKind.Utc),
                            Email = "siti.aminah@pens.ac.id",
                            IsDeleted = false,
                            Name = "Siti Aminah",
                            Phone = "081234567891",
                            Status = "active"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a1b2-4c7d-0e1f-2a3b4c5d6e7f"),
                            Address = "Keputih Tegal Gg. III",
                            CreatedDate = new DateTime(2026, 2, 3, 9, 15, 0, 0, DateTimeKind.Utc),
                            Email = "andi.wijaya@pens.ac.id",
                            IsDeleted = false,
                            Name = "Andi Wijaya",
                            Phone = "081234567892",
                            Status = "inactive"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a1-b2c3-4d8e-1f2a-3b4c5d6e7f8a"),
                            Address = "Mulyosari Permai No. 45",
                            CreatedDate = new DateTime(2026, 2, 4, 14, 20, 0, 0, DateTimeKind.Utc),
                            Email = "rina.rose@pens.ac.id",
                            IsDeleted = false,
                            Name = "Rina Rose",
                            Phone = "081234567893",
                            Status = "active"
                        },
                        new
                        {
                            Id = new Guid("e5f6a1b2-c3d4-4e9f-2a3b-4c5d6e7f8a9b"),
                            Address = "Asrama Mahasiswa PENS",
                            CreatedDate = new DateTime(2026, 2, 5, 16, 45, 0, 0, DateTimeKind.Utc),
                            Email = "eko.prasetyo@pens.ac.id",
                            IsDeleted = false,
                            Name = "Eko Prasetyo",
                            Phone = "081234567894",
                            Status = "active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
