// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SparkPens.Api.Data;

#nullable disable

namespace SparkPens.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SparkPens.Api.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NIM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaMahasiswa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WaktuMulai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WaktuSelesai")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Keperluan = "Latihan ASP.NET Core",
                            NIM = "21102030",
                            NamaMahasiswa = "Kratos Spartan",
                            NamaRuangan = "Lab Programming 1",
                            Status = "Approved",
                            WaktuMulai = new DateTime(2026, 2, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            WaktuSelesai = new DateTime(2026, 2, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
